/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginDetailForm.java
 *
 * Created on Jan 17, 2011, 5:27:55 AM
 */

package studentserver;

import studentclient.*;
import Common.PrivilegeMode;
import Common.Lecturer;
import Common.Person;
import Common.Student;
import Common.Functionality;
import javax.swing.JOptionPane;

/**
 *
 * @author Thushan
 */
public class LoginDetailForm extends javax.swing.JDialog {

    /** Creates new form LoginDetailForm */
    private static PrivilegeMode mode;
    public LoginDetailForm(PrivilegeMode amode) {
        mode=amode;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passText = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        unameText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        confirmPassText = new javax.swing.JPasswordField();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("Password:");

        jLabel8.setText("Username:");

        unameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Confirm password:");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passText, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(unameText)
                    .addComponent(confirmPassText, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(unameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(confirmPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_unameTextActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        Person currentPerson=null;
        Boolean isMatch=false;

        if(mode==PrivilegeMode.Student){
            Student student=new Student();
            student.setUserName(unameText.getText());
            student.setPrivilegeMode(mode);
            currentPerson=student;

        }
        else if(mode== PrivilegeMode.Lecturer){
            Lecturer lecturer=new Lecturer();
            lecturer.setUserName(unameText.getText());
            lecturer.setPrivilegeMode(mode);
            currentPerson=lecturer;
        }
        else if(mode== PrivilegeMode.Administrator){
            currentPerson=new Person();
            currentPerson.setUserName(unameText.getText());
        }

        //Check password confirmed password match
        if(PasswordEncorder.encrypt(new String(passText.getPassword())).equals(PasswordEncorder.encrypt(new String(confirmPassText.getPassword())))){
            isMatch=true;
        }
        else{
            isMatch=false;
        }

        System.out.println(currentPerson.getUserName()+"KDLFJLS");
        if(unameText.getText().isEmpty() || (new String(passText.getPassword())).isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out all the fields");
        } else if(DatabaseHandler.similarUserName(currentPerson.getUserName())){
            JOptionPane.showMessageDialog(null,"User with similar username exists");
        } else if(!isMatch){
            JOptionPane.showMessageDialog(null, "Passwords doesn't match");
        } else if(!DatabaseHandler.similarUserName(currentPerson.getUserName()) && isMatch && mode != PrivilegeMode.Administrator) {
            DatabaseHandler.addNewUserLogin(currentPerson.getUserName(), PasswordEncorder.encrypt(new String(passText.getPassword())), mode);
            FrameHandler.showProfileDetailForm(currentPerson,Functionality.NEW);
            this.dispose();
        }else if(isMatch && mode == PrivilegeMode.Administrator){
            DatabaseHandler.addNewUserLogin(unameText.getText(), PasswordEncorder.encrypt(new String(passText.getPassword())), mode);
            this.dispose();
        }

        unameText.setText("");
        passText.setText("");
        confirmPassText.setText("");


    }//GEN-LAST:event_nextButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDetailForm dialog = new LoginDetailForm(mode);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nextButton;
    private javax.swing.JPasswordField passText;
    private javax.swing.JTextField unameText;
    // End of variables declaration//GEN-END:variables

}
