/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdvanceSearchForm.java
 *
 * Created on Jan 17, 2011, 1:06:07 PM
 */

package studentclient;

import Common.DataTable;
import Common.DatabaseEntry;
import Common.Functionality;
import Common.Lecturer;
import Common.StudyAreas;
import Common.Person;

import Common.Student;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Thushan
 */
public class AdvanceSearchForm extends javax.swing.JDialog {

    /** Creates new form AdvanceSearchForm */
    private static SearchNSortForm ssForm;
    ArrayList<Person> searchResult;
    public AdvanceSearchForm(SearchNSortForm aSsForm) {
        ssForm=aSsForm;
        searchResult=new ArrayList<Person>();
        initComponents();

        interestCombo.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        indNoText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telNoText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addrText = new javax.swing.JTextField();
        studentCheck = new javax.swing.JCheckBox();
        lecturerCheck = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        interestCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Last name:");

        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        jLabel2.setText("First name:");

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        jLabel8.setText("IndexNo:");

        indNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indNoTextActionPerformed(evt);
            }
        });

        jLabel6.setText("Telephone No:");

        telNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNoTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Home address:");

        addrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrTextActionPerformed(evt);
            }
        });

        studentCheck.setSelected(true);
        studentCheck.setText("Students");
        studentCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCheckActionPerformed(evt);
            }
        });

        lecturerCheck.setText("Lecturers");
        lecturerCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerCheckActionPerformed(evt);
            }
        });

        jLabel3.setText("Database: ");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Interest:");

        interestCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PROGRAMMING", "ALGORITHMS", "SECURITY", "NETWORKING", "HARDWARE", "OTHER" }));
        interestCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel3))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                            .addComponent(lastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(studentCheck)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lecturerCheck)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(indNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(addrText, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(interestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentCheck)
                    .addComponent(lecturerCheck)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(indNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(searchButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(interestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_lastNameTextActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_firstNameTextActionPerformed

    private void indNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indNoTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_indNoTextActionPerformed

    private void telNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNoTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_telNoTextActionPerformed

    private void addrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_addrTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
       
        if(studentCheck.isSelected() && !lecturerCheck.isSelected()){
            Student student=new Student(new String[]{null,lastNameText.getText()},firstNameText.getText(),indNoText.getText(),null,addrText.getText(),telNoText.getText(),null,0);
            searchResult=(ArrayList<Person>)ServerSend.sendMessage(new DatabaseEntry(Functionality.SEARCH_MULTIPLE, student, null, DataTable.Students));
            ssForm.displayInTable(searchResult, DataTable.Students);
            
        }
        if(!studentCheck.isSelected() && lecturerCheck.isSelected()){
            StudyAreas sArea = null;
            if(interestCombo.getSelectedIndex()==0)
                sArea=StudyAreas.PROGRAMMING;
            else if(interestCombo.getSelectedIndex()==1)
                sArea=StudyAreas.ALGORITHMS;
            else if(interestCombo.getSelectedIndex()==2)
                sArea=StudyAreas.SECURITY;
            else if(interestCombo.getSelectedIndex()==3)
                sArea=StudyAreas.NETWORKING;
            else if(interestCombo.getSelectedIndex()==4)
                sArea=StudyAreas.HARDWARE;
            else if(interestCombo.getSelectedIndex()==5)
                sArea=StudyAreas.OTHER;

            Lecturer lecturer=new Lecturer(new String[]{null,lastNameText.getText()},firstNameText.getText(),null,addrText.getText(),telNoText.getText(),null,null,sArea,0);
            searchResult=(ArrayList<Person>)ServerSend.sendMessage(new DatabaseEntry(Functionality.SEARCH_MULTIPLE, lecturer, null, DataTable.Lecturers));
            ssForm.displayInTable(searchResult, DataTable.Lecturers);
        }
        if(studentCheck.isSelected() && lecturerCheck.isSelected()){
            Person person=new Person(new String[]{null,lastNameText.getText()},firstNameText.getText(),null,addrText.getText(),telNoText.getText(),null,0);
            searchResult=(ArrayList<Person>)ServerSend.sendMessage(new DatabaseEntry(Functionality.SEARCH_MULTIPLE, person, null, DataTable.StudentsAndLectureres));
            ssForm.displayInTable(searchResult, DataTable.StudentsAndLectureres);
        }

        if(!studentCheck.isSelected() && !lecturerCheck.isSelected()){
            JOptionPane.showMessageDialog(null, "Please select a database to search");
        }

        if(searchResult.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sorry, No matches found");
        }

        clearTextFields();
        this.dispose();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void lecturerCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerCheckActionPerformed
        // TODO add your handling code here:
        if(lecturerCheck.isSelected())
            indNoText.setEnabled(false);
        else
            indNoText.setEnabled(true);
    }//GEN-LAST:event_lecturerCheckActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clearTextFields();
        dispose();

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void interestComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestComboActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_interestComboActionPerformed

    private void studentCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCheckActionPerformed
        // TODO add your handling code here:
        if(studentCheck.isSelected())
            interestCombo.setEnabled(false);
        else
            interestCombo.setEnabled(true);
    }//GEN-LAST:event_studentCheckActionPerformed

    private void clearTextFields(){
        lastNameText.setText("");
        firstNameText.setText("");
        indNoText.setText("");
        addrText.setText("");
        telNoText.setText("");
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdvanceSearchForm dialog = new AdvanceSearchForm(ssForm);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JTextField indNoText;
    private javax.swing.JComboBox interestCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JCheckBox lecturerCheck;
    private javax.swing.JButton searchButton;
    private javax.swing.JCheckBox studentCheck;
    private javax.swing.JTextField telNoText;
    // End of variables declaration//GEN-END:variables

}
