/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProfileDetailForm.java
 *
 * Created on Jan 16, 2011, 10:29:47 PM
 */
package studentclient;

import Common.Gender;
import Common.PrivilegeMode;
import Common.Properties;
import Common.DataTable;
import Common.DatabaseEntry;
import Common.Lecturer;
import Common.StudyAreas;
import Common.Person;
import Common.Student;
import Common.Functionality;
import Common.Qualifications;
import Common.UserDB;
import java.awt.Image;

import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Thushan
 */
public class ProfileDetailForm extends javax.swing.JDialog {

    private static Person person;
    private File image;
    private static Functionality func;
    //private static Person updatePer;

    /** Creates new form ProfileDetailForm */
    public ProfileDetailForm(Person aperson, Functionality afunc) {
        func = afunc;
        person = aperson;
        initComponents();
        String[] date = new String[31];
        String[] month = new String[12];
        String[] year = new String[50];

        for (int i = 0; i < 31; i++) {
            date[i] = Integer.toString(i + 1);
        }
        for (int i = 0; i < 12; i++) {
            month[i] = Integer.toString(i + 1);
        }
        for (int i = 0; i < 50; i++) {
            year[i] = Integer.toString(i + 1950);
        }

        dateCombo.setModel(new DefaultComboBoxModel(date));
        monthCombo.setModel(new DefaultComboBoxModel(month));
        yearCombo.setModel(new DefaultComboBoxModel(year));

        //Adapt the form according to the priviledge mode
        if (person.getPrivilegeMode() == PrivilegeMode.Student) {
            indNoText.setEnabled(true);
            semesterCombo.setEnabled(true);
            qualificationCombo.setEnabled(false);
            interestCombo.setEnabled(false);
        } else if (person.getPrivilegeMode() == PrivilegeMode.Lecturer) {
            indNoText.setEnabled(false);
            semesterCombo.setEnabled(false);
            qualificationCombo.setEnabled(true);
            interestCombo.setEnabled(true);
        }

        if (func == Functionality.UPDATE) {
            //person = null;
            DataTable dTable = null;
            if (person.getPrivilegeMode() == PrivilegeMode.Student) {
                dTable = DataTable.Students;
            } else if (person.getPrivilegeMode() == PrivilegeMode.Lecturer) {
                dTable = DataTable.Lecturers;
            }

            person = (Person) ServerSend.sendMessage(new DatabaseEntry(Functionality.SEARCH_USER, person, Properties.UserName, dTable));

            setAllFields(person);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        initText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        telNoText = new javax.swing.JTextField();
        addrText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox();
        monthCombo = new javax.swing.JComboBox();
        yearCombo = new javax.swing.JComboBox();
        indNoText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        semesterCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        lastNameText = new javax.swing.JTextField();
        uploadButton = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        imgPathLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        qualificationCombo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        interestCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel3.setText("Date of birth:");

        initText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Name with initials: ");

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Image:");

        jLabel2.setText("First name:");

        telNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNoTextActionPerformed(evt);
            }
        });

        addrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Gender:");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel6.setText("Telephone No:");

        jLabel4.setText("Home address:");

        indNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indNoTextActionPerformed(evt);
            }
        });

        jLabel8.setText("IndexNo:");

        semesterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8" }));
        semesterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterComboActionPerformed(evt);
            }
        });

        jLabel9.setText("Semester:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save & Close");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Qualifications:");

        qualificationCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BSc", "MSc", "Phd" }));
        qualificationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualificationComboActionPerformed(evt);
            }
        });

        jLabel11.setText("Interest:");

        interestCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PROGRAMMING", "ALGORITHMS", "SECURITY", "NETWORKING", "HARDWARE", "OTHER" }));
        interestCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(interestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(qualificationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(semesterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(indNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(uploadButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(imgPathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                                            .addComponent(genderCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addrText, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(firstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                            .addComponent(telNoText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(initText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                                        .addGap(15, 15, 15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(initText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(indNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(semesterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(uploadButton)
                    .addComponent(imgPathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(qualificationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(interestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_initTextActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_firstNameTextActionPerformed

    private void telNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNoTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_telNoTextActionPerformed

    private void addrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_addrTextActionPerformed

    private void indNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indNoTextActionPerformed

    private void semesterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterComboActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Student student;
        Lecturer lecturer;

        String[] nameWithInit = {initText.getText(), lastNameText.getText()};
        person.setNameWithInit(nameWithInit);
        person.setFirstName(firstNameText.getText());
        int[] bday = {(dateCombo.getSelectedIndex() + 1), (monthCombo.getSelectedIndex() + 1), (yearCombo.getSelectedIndex() + 1951)};
        person.setDateOfBirth(bday);
        person.setAddress(addrText.getText());

        if (genderCombo.getSelectedIndex() == 0) {
            person.setGender(Gender.Male);
        } else if (genderCombo.getSelectedIndex() == 1) {
            person.setGender(Gender.Female);
        }

        person.setTelNo(telNoText.getText());

        if (person.getPrivilegeMode() == PrivilegeMode.Student) {
            student = (Student) person;
            student.setIndexNo(indNoText.getText());
            student.setSemester(semesterCombo.getSelectedIndex() + 1);
        }

        if (person.getPrivilegeMode() == PrivilegeMode.Lecturer) {
            lecturer = (Lecturer) person;
            if (qualificationCombo.getSelectedIndex() == 0) {
                lecturer.setQualification(Qualifications.BSc);
            } else if (qualificationCombo.getSelectedIndex() == 1) {
                lecturer.setQualification(Qualifications.MSc);
            } else if (qualificationCombo.getSelectedIndex() == 2) {
                lecturer.setQualification(Qualifications.Phd);
            }

            if (interestCombo.getSelectedIndex() == 0) {
                lecturer.setStudyArea(StudyAreas.PROGRAMMING);
            } else if (interestCombo.getSelectedIndex() == 1) {
                lecturer.setStudyArea(StudyAreas.ALGORITHMS);
            } else if (interestCombo.getSelectedIndex() == 2) {
                lecturer.setStudyArea(StudyAreas.SECURITY);
            } else if (interestCombo.getSelectedIndex() == 3) {
                lecturer.setStudyArea(StudyAreas.NETWORKING);
            } else if (interestCombo.getSelectedIndex() == 4) {
                lecturer.setStudyArea(StudyAreas.HARDWARE);
            } else if (interestCombo.getSelectedIndex() == 4) {
                lecturer.setStudyArea(StudyAreas.OTHER);
            }
        }



        if (!isFieldEmpty(person.getPrivilegeMode())) {
            if (func == Functionality.NEW) {
                ServerSend.sendMessage(new DatabaseEntry(Functionality.NEWPROFILE, person, null, null));
            } else if (func == Functionality.UPDATE) {
                ServerSend.sendMessage(new DatabaseEntry(Functionality.UPDATE, person, null, null));
            }

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please fill out all the fields");
        }


    }//GEN-LAST:event_saveButtonActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser imgChooser = new JFileChooser();
        imgChooser.showOpenDialog(null);
        image = imgChooser.getSelectedFile();
        

        if ((image.length() / 1024) < 100) {
            if (imgPathLabel != null) {
                imgPathLabel.setText(image.getPath());
                imgLabel.setIcon(FrameHandler.resizeImg(image, imgLabel));
            }
            person.setImgFile(image);
        } else {
            JOptionPane.showMessageDialog(null, "File is too large (>100KB). Please select a different file");
        }


    }//GEN-LAST:event_uploadButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void qualificationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualificationComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualificationComboActionPerformed

    private void interestComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestComboActionPerformed

    private boolean isFieldEmpty(PrivilegeMode mode) {
        if (mode == PrivilegeMode.Student) {
            if (initText.getText().isEmpty() || firstNameText.getText().isEmpty() || addrText.getText().isEmpty() || indNoText.getText().isEmpty()) {
                return true;
            }
            return false;

        } else if (mode == PrivilegeMode.Lecturer) {
            if (initText.getText().isEmpty() || firstNameText.getText().isEmpty() || addrText.getText().isEmpty()) {
                return true;
            }
            return false;
        }

        return true;
    }

    private void setAllFields(Person person) {

        initText.setText(person.getNameAndInits()[0]);
        lastNameText.setText(person.getNameAndInits()[1]);
        firstNameText.setText(person.getFirstName());

        dateCombo.setSelectedIndex(person.getDateOfBirth()[0] - 1);
        monthCombo.setSelectedIndex(person.getDateOfBirth()[1] - 1);
        yearCombo.setSelectedIndex(person.getDateOfBirth()[2] - 1);

        addrText.setText(person.getAddress());
        telNoText.setText(person.getTelNo());
        imgLabel.setIcon(FrameHandler.resizeImg((ImageIcon) ServerSend.sendMessage(new UserDB(person.getUserName(), null, Functionality.RETRIEVE_IMAGE, null)), imgLabel));
        if (person.getGender() == Gender.Male) {
            genderCombo.setSelectedIndex(0);
        } else if (person.getGender() == Gender.Female) {
            genderCombo.setSelectedIndex(1);
        }

        if (person.getPrivilegeMode() == PrivilegeMode.Student) {
            indNoText.setText(((Student) person).getIndexNo());
        } else if (person.getPrivilegeMode() == PrivilegeMode.Lecturer) {
            //set combo boxes to correct values
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ProfileDetailForm dialog = new ProfileDetailForm(person, func);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox dateCombo;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JComboBox genderCombo;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel imgPathLabel;
    private javax.swing.JTextField indNoText;
    private javax.swing.JTextField initText;
    private javax.swing.JComboBox interestCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JComboBox monthCombo;
    private javax.swing.JComboBox qualificationCombo;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox semesterCombo;
    private javax.swing.JTextField telNoText;
    private javax.swing.JButton uploadButton;
    private javax.swing.JComboBox yearCombo;
    // End of variables declaration//GEN-END:variables
}
