/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartForm.java
 *
 * Created on Jan 16, 2011, 9:02:53 PM
 */

package studentclient;

import Common.PrivilegeMode;
import Common.Properties;
import Common.DataTable;
import Common.DatabaseEntry;
import Common.Exit;
import Common.Person;
import Common.Functionality;
import java.util.ArrayList;

/**
 *
 * @author Thushan
 */
public class StartForm extends javax.swing.JFrame {

    /** Creates new form StartForm */
    private static PrivilegeMode mode;
    private static String uname;
    public StartForm(String auname,PrivilegeMode amode) {
        uname=auname;
        mode=amode;
        initComponents();

        if(mode==PrivilegeMode.Student || mode==PrivilegeMode.Lecturer){
            newMenu.setEnabled(false);
            sortItem.setEnabled(false);
            searchItem.setEnabled(false);
            deleteMenu.setEnabled(false);
            updateItem.setEnabled(false);

        }else if(mode==PrivilegeMode.Administrator){
            newMenu.setEnabled(true);
            sortItem.setEnabled(true);
            searchItem.setEnabled(true);
            deleteMenu.setEnabled(true);
            updateItem.setEnabled(true);
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenu = new javax.swing.JMenu();
        studentItem = new javax.swing.JMenuItem();
        lecturerItem = new javax.swing.JMenuItem();
        deleteMenu = new javax.swing.JMenu();
        delStudentItem = new javax.swing.JMenuItem();
        delLecturerItem = new javax.swing.JMenuItem();
        logoutItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editProfileItem = new javax.swing.JMenuItem();
        updateItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewProfileItem = new javax.swing.JMenuItem();
        searchItem = new javax.swing.JMenuItem();
        sortItem = new javax.swing.JMenuItem();
        topNewsItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();
        helpItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/startpage.jpg"))); // NOI18N

        fileMenu.setText("File");

        newMenu.setText("New");

        studentItem.setText("Student");
        studentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentItemActionPerformed(evt);
            }
        });
        newMenu.add(studentItem);

        lecturerItem.setText("Lecturer");
        lecturerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerItemActionPerformed(evt);
            }
        });
        newMenu.add(lecturerItem);

        fileMenu.add(newMenu);

        deleteMenu.setText("Delete");

        delStudentItem.setText("Student");
        delStudentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStudentItemActionPerformed(evt);
            }
        });
        deleteMenu.add(delStudentItem);

        delLecturerItem.setText("Lecturer");
        delLecturerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delLecturerItemActionPerformed(evt);
            }
        });
        deleteMenu.add(delLecturerItem);

        fileMenu.add(deleteMenu);

        logoutItem.setText("Log out");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        fileMenu.add(logoutItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        editProfileItem.setText("Edit my profile");
        editProfileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileItemActionPerformed(evt);
            }
        });
        editMenu.add(editProfileItem);

        updateItem.setText("Update");
        updateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateItemActionPerformed(evt);
            }
        });
        editMenu.add(updateItem);

        jMenuBar1.add(editMenu);

        viewMenu.setText("View");

        viewProfileItem.setText("View my profile");
        viewProfileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileItemActionPerformed(evt);
            }
        });
        viewMenu.add(viewProfileItem);

        searchItem.setText("Search");
        searchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemActionPerformed(evt);
            }
        });
        viewMenu.add(searchItem);

        sortItem.setText("Sort");
        sortItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortItemActionPerformed(evt);
            }
        });
        viewMenu.add(sortItem);

        topNewsItem.setText("Add top news");
        topNewsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topNewsItemActionPerformed(evt);
            }
        });
        viewMenu.add(topNewsItem);

        jMenuBar1.add(viewMenu);

        helpMenu.setText("Help");

        aboutItem.setText("About");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutItem);

        helpItem.setText("Help");
        helpMenu.add(helpItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showLoginDetailForm(PrivilegeMode.Student);
    }//GEN-LAST:event_studentItemActionPerformed

    private void searchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showSearchNSortForm(Functionality.SEARCH_SINGLE);
    }//GEN-LAST:event_searchItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showLoginForm();
        ServerSend.sendMessage(new Exit());
        this.dispose();
    }//GEN-LAST:event_logoutItemActionPerformed

    private void viewProfileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showViewProfileForm(uname,mode);
    }//GEN-LAST:event_viewProfileItemActionPerformed

    private void delStudentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStudentItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showSearchNSortForm(Functionality.DELETEStudent);
    }//GEN-LAST:event_delStudentItemActionPerformed

    private void sortItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showSearchNSortForm(Functionality.SORT); 
    }//GEN-LAST:event_sortItemActionPerformed

    private void updateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showSearchNSortForm(Functionality.UPDATE);
    }//GEN-LAST:event_updateItemActionPerformed

    private void lecturerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showLoginDetailForm(PrivilegeMode.Lecturer);
    }//GEN-LAST:event_lecturerItemActionPerformed

    private void editProfileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileItemActionPerformed
        // TODO add your handling code here:
        Person person=null;
        if(mode==PrivilegeMode.Student)
            person=((ArrayList<Person>)ServerSend.sendMessage(new DatabaseEntry(Functionality.SEARCH_SINGLE,new Person(uname), Properties.UserName, DataTable.Students))).get(0);

        else if(mode==PrivilegeMode.Student)
            person=((ArrayList<Person>)ServerSend.sendMessage(new DatabaseEntry(Functionality.SEARCH_SINGLE,new Person(uname), Properties.UserName, DataTable.Lecturers))).get(0);

        FrameHandler.showProfileDetailForm(person,Functionality.UPDATE);
    }//GEN-LAST:event_editProfileItemActionPerformed

    private void delLecturerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delLecturerItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showSearchNSortForm(Functionality.DELETELecturer);
    }//GEN-LAST:event_delLecturerItemActionPerformed

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        // TODO add your handling code here:
        FrameHandler.showAboutForm();
    }//GEN-LAST:event_aboutItemActionPerformed

    private void topNewsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topNewsItemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_topNewsItemActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartForm dialog = new StartForm(uname,mode);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {                       
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem delLecturerItem;
    private javax.swing.JMenuItem delStudentItem;
    private javax.swing.JMenu deleteMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editProfileItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem helpItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem lecturerItem;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenu newMenu;
    private javax.swing.JMenuItem searchItem;
    private javax.swing.JMenuItem sortItem;
    private javax.swing.JMenuItem studentItem;
    private javax.swing.JMenuItem topNewsItem;
    private javax.swing.JMenuItem updateItem;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem viewProfileItem;
    // End of variables declaration//GEN-END:variables

}
